"""
PDF export for a two-company comparison result.

Formats an already-computed comparison result (shared people, sanctions
matches, infrastructure overlaps, confidence level) as a downloadable
PDF -- a real due-diligence artifact someone could file, print, or
email, rather than just a webpage that disappears when the tab closes.
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import HRFlowable, ListFlowable, ListItem, Paragraph, SimpleDocTemplate, Spacer

CONFIDENCE_LABELS = {
    "high": "HIGH CONFIDENCE -- corroborated by both ownership and infrastructure evidence",
    "low": "LOW CONFIDENCE -- supported by one type of evidence; recommend manual review",
    "none": "NO CONNECTION FOUND",
}


def build_comparison_pdf(
    output_path: str,
    company_a_name: str,
    company_b_name: str,
    confidence: str,
    shared_people: list[str],
    sanctions_matches: list[dict],
    infra_overlaps: list[str],
    infra_note: str | None,
) -> str:
    """Build a PDF report for a two-company comparison result.

    Args:
        output_path: Where to write the PDF file.
        company_a_name: First company's name.
        company_b_name: Second company's name.
        confidence: "high", "low", or "none".
        shared_people: Names shared as officer/PSC between both companies.
        sanctions_matches: Flagged OFAC matches, as returned by
            screen_beneficial_owners().
        infra_overlaps: Infrastructure overlap findings, as plain strings.
        infra_note: Any caveat about the infrastructure check (skipped,
            partially failed, same-domain warning, etc.), or None.

    Returns:
        The output_path, for convenience.
    """
    doc = SimpleDocTemplate(output_path, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="ReportBody", parent=styles["Normal"], spaceAfter=6, leading=14))
    styles.add(ParagraphStyle(name="Small", parent=styles["Normal"], fontSize=9, textColor=colors.HexColor("#555555")))

    story = []

    story.append(Paragraph("SNDOIF -- Company Comparison Report", styles["Title"]))
    story.append(Paragraph(f"{company_a_name} vs {company_b_name}", styles["Heading2"]))
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 12))

    confidence_color = {"high": "#e63946", "low": "#c1660a", "none": "#2a9d8f"}.get(confidence, "#000000")
    story.append(Paragraph(
        f'<font color="{confidence_color}"><b>{CONFIDENCE_LABELS.get(confidence, confidence.upper())}</b></font>',
        styles["ReportBody"],
    ))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Shared Directors / PSCs", styles["Heading3"]))
    if shared_people:
        story.append(ListFlowable(
            [ListItem(Paragraph(name, styles["ReportBody"])) for name in shared_people],
            bulletType="bullet",
        ))
    else:
        story.append(Paragraph("No shared officers or beneficial owners found.", styles["ReportBody"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Sanctions Screening", styles["Heading3"]))
    if sanctions_matches:
        items = [
            Paragraph(
                f"{m['screened_name']} ~ {m['matched_name']} (similarity score {m['score']:.1f})",
                styles["ReportBody"],
            )
            for m in sanctions_matches
        ]
        story.append(ListFlowable([ListItem(i) for i in items], bulletType="bullet"))
    else:
        story.append(Paragraph("No sanctions matches found for either company.", styles["ReportBody"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Infrastructure Overlap", styles["Heading3"]))
    if infra_note:
        story.append(Paragraph(infra_note, styles["Small"]))
        story.append(Spacer(1, 4))
    if infra_overlaps:
        story.append(ListFlowable(
            [ListItem(Paragraph(item, styles["ReportBody"])) for item in infra_overlaps],
            bulletType="bullet",
        ))
    else:
        story.append(Paragraph("No infrastructure overlap found.", styles["ReportBody"]))

    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Generated by SNDOIF. This is an automated screening result intended to support, "
        "not replace, human due-diligence review. Flagged connections should be independently verified.",
        styles["Small"],
    ))

    doc.build(story)
    return output_path
