"""
PDF export for SNDOIF results.

Formats an already-computed result (either a two-company comparison or
a single-company search) as a downloadable PDF -- a real due-diligence
artifact someone could file, print, or email, rather than just a
webpage that disappears when the tab closes.
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import HRFlowable, ListFlowable, ListItem, Paragraph, SimpleDocTemplate, Spacer

CONFIDENCE_LABELS = {
    "high": "HIGH CONFIDENCE -- corroborated by both ownership and infrastructure evidence",
    "low": "LOW CONFIDENCE -- supported by one type of evidence; recommend manual review",
    "none": "NO CONNECTION FOUND",
}


def _base_styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="ReportBody", parent=styles["Normal"], spaceAfter=6, leading=14))
    styles.add(ParagraphStyle(name="Small", parent=styles["Normal"], fontSize=9, textColor=colors.HexColor("#555555")))
    return styles


def _bullet_list(items: list[str], styles) -> ListFlowable:
    return ListFlowable(
        [ListItem(Paragraph(item, styles["ReportBody"])) for item in items],
        bulletType="bullet",
    )


def build_comparison_pdf(
    output_path: str,
    company_a_name: str,
    company_b_name: str,
    confidence: str,
    shared_people: list[str],
    sanctions_matches: list[dict],
    infra_overlaps: list[str],
    infra_note: str | None,
) -> str:
    """Build a PDF report for a two-company comparison result."""
    doc = SimpleDocTemplate(output_path, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = _base_styles()
    story = []

    story.append(Paragraph("SNDOIF -- Company Comparison Report", styles["Title"]))
    story.append(Paragraph(f"{company_a_name} vs {company_b_name}", styles["Heading2"]))
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 12))

    confidence_color = {"high": "#e63946", "low": "#c1660a", "none": "#2a9d8f"}.get(confidence, "#000000")
    story.append(Paragraph(
        f'<font color="{confidence_color}"><b>{CONFIDENCE_LABELS.get(confidence, confidence.upper())}</b></font>',
        styles["ReportBody"],
    ))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Shared Directors / PSCs", styles["Heading3"]))
    if shared_people:
        story.append(_bullet_list(shared_people, styles))
    else:
        story.append(Paragraph("No shared officers or beneficial owners found.", styles["ReportBody"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Sanctions Screening", styles["Heading3"]))
    if sanctions_matches:
        items = [
            f"{m['screened_name']} ~ {m['matched_name']} (similarity score {m['score']:.1f})"
            for m in sanctions_matches
        ]
        story.append(_bullet_list(items, styles))
    else:
        story.append(Paragraph("No sanctions matches found for either company.", styles["ReportBody"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Infrastructure Overlap", styles["Heading3"]))
    if infra_note:
        story.append(Paragraph(infra_note, styles["Small"]))
        story.append(Spacer(1, 4))
    if infra_overlaps:
        story.append(_bullet_list(infra_overlaps, styles))
    else:
        story.append(Paragraph("No infrastructure overlap found.", styles["ReportBody"]))

    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Generated by SNDOIF. This is an automated screening result intended to support, "
        "not replace, human due-diligence review. Flagged connections should be independently verified.",
        styles["Small"],
    ))

    doc.build(story)
    return output_path


def build_search_pdf(
    output_path: str,
    company_name: str,
    company_number: str,
    company_status: str,
    officer_count: int,
    psc_count: int,
    sanctions_matches: list[dict],
    shared_directors: list[dict],
    jurisdiction_flags: list[dict],
    scored_pairs: list[dict],
    infra_note: str,
) -> str:
    """Build a PDF report for a single-company search result.

    Args:
        output_path: Where to write the PDF file.
        company_name, company_number, company_status: Basic profile fields.
        officer_count, psc_count: Counts from the OwnershipRecord.
        sanctions_matches: Flagged OFAC matches for this company's people.
        shared_directors: Shared-director red flags involving this company.
        jurisdiction_flags: FATF jurisdiction flags for this company's PSCs.
        scored_pairs: Fusion-scored connections involving this company.
        infra_note: Caveat about infrastructure checks (skipped/failed/etc).

    Returns:
        The output_path, for convenience.
    """
    doc = SimpleDocTemplate(output_path, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = _base_styles()
    story = []

    story.append(Paragraph("SNDOIF -- Company Search Report", styles["Title"]))
    story.append(Paragraph(company_name, styles["Heading2"]))
    story.append(Paragraph(
        f"Company number {company_number} &nbsp;|&nbsp; Status: {company_status} &nbsp;|&nbsp; "
        f"{officer_count} officers, {psc_count} PSC records",
        styles["Small"],
    ))
    story.append(Spacer(1, 8))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Sanctions Screening", styles["Heading3"]))
    if sanctions_matches:
        items = [
            f"{m['screened_name']} ~ {m['matched_name']} (similarity score {m['score']:.1f})"
            for m in sanctions_matches
        ]
        story.append(_bullet_list(items, styles))
    else:
        story.append(Paragraph("No sanctions matches found.", styles["ReportBody"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Shared Director Red Flags", styles["Heading3"]))
    if shared_directors:
        items = [f"{f['person']}: linked to {f['company_count']} companies" for f in shared_directors]
        story.append(_bullet_list(items, styles))
    else:
        story.append(Paragraph("None found.", styles["ReportBody"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Jurisdiction Red Flags", styles["Heading3"]))
    if jurisdiction_flags:
        items = [f"PSC {f['psc_name']} registered in {f['jurisdiction']}" for f in jurisdiction_flags]
        story.append(_bullet_list(items, styles))
    else:
        story.append(Paragraph("None found.", styles["ReportBody"]))
    story.append(Spacer(1, 10))

    story.append(Paragraph("Connections to Known Companies", styles["Heading3"]))
    if infra_note:
        story.append(Paragraph(infra_note, styles["Small"]))
        story.append(Spacer(1, 4))
    if scored_pairs:
        items = [
            f"{p['confidence'].upper()} confidence: {p['company_a']} <-> {p['company_b']}"
            for p in scored_pairs
        ]
        story.append(_bullet_list(items, styles))
    else:
        story.append(Paragraph("No connections found to other known companies.", styles["ReportBody"]))

    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#cccccc")))
    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Generated by SNDOIF. This is an automated screening result intended to support, "
        "not replace, human due-diligence review. Flagged connections should be independently verified.",
        styles["Small"],
    ))

    doc.build(story)
    return output_path
